### PR TITLE
Feature/transfer rewards#47

### LINKED ISSUE #47: [Rewards] Transfer rewards functionality
### AC
- add functionality to call node API endpoint for reward transfers.

### PR DESCRIPTION
**Pull request by 0xean**
Adds functionality to sign reward transfer object and send to node. closes #47 and #49

### CODE REVIEW

**Comment by 0xean** [comment]
add the static fields to this class seems to have broken our linting.

**Review by dmvt — COMMENTED** [review]
Looking good... just the one incorrect comment version

**Comment by 0xean** [comment]
now depends on #54 - will rebase once that is merged.

**Review by lrsaturnino — DISMISSED** [review]
LGTM

**Review by lrsaturnino — COMMENTED** [review]
LGTM

**Pull request merged**
